### ISSUE TITLE
I cannot make reconnection for Queries work correctly.

### ISSUE THREAD

**Issue by Neo1975** [kubemq-io/kubemq-js#1]
Hi,
I'm not sure this is a bug but I have some problem trying to use reconnection feature.

I'm testing two different situation:
1- start a receiver without an instance of kubemq
2- start a receiver with an instance of kubemq and shoutdown it after connection of receiver.

Looking in the code

```javascript
                while (!unsubscribe) {
                    onStateChange.emit('connecting');
                    yield this.subscribeFn(request, cb).then((value) => {
                        value.onClose.on(() => {
                            isClosed = true;
                            onStateChange.emit('disconnected');
                        });
                        currentStream = value.stream;
                    });
                    let isClosed = false;
                    onStateChange.emit('connected');
                    while (!isClosed && !unsubscribe) {
                        yield new Promise((r) => setTimeout(r, 1000));
                    }
                    const reconnectionInterval = this.clientOptions.reconnectInterval;
                    if (reconnectionInterval === 0) {
                        unsubscribe = true;
                    }
                    else {
                        yield new Promise((r) => setTimeout(r, reconnectionInterval));
                    }
                }
```

`isClosed` can become true only if event `value.onClose` is triggered that happens only if:

```javascript
            stream.on('close', () => {
                onClose.emit();
            });
```

In my previous scenario instead only

```javascript
            stream.on('error', (e) => {
                cb(e, null);
            });
```
is triggered.

I also tried to call `client.close()` in my callback `cb`, without success.

Looking better deeply in the code I think that `stream` never emit a `close`.

Can you help me?

**Comment by kubemq** [comment]
Thank you,
Will merge your PR

**Comment by ukaoskid** [comment]
@Neo1975 @kubemq I am still facing this problem, but it's probably because I haven't understood how to manage the client close on error. (same scenarios like starting receivers when server is down, or when server goes down)

Do you have any example?
