### ISSUE TITLE
"QueuesDownstreamResponse Received" console log clutters up our logs

### ISSUE THREAD

**Issue by juliusdeblaaij** [kubemq-io/kubemq-js#13]
There is a built in message starting with "QueuesDownstreamResponse Received" which is a console.log statement in the shipped version of this repo.
Please remove it as it is making our logs exceptionally long and hard too read.

**Comment by kubemq** [comment]
Hi,
Thanks for the heads up.
We have released version 2.1.0 that removes all console.log writing.
Let me know if you still see the issue.
